
package perez;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "perez_metodo", targetNamespace = "http://perez/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PerezMetodo {


    /**
     * 
     * @param catA
     * @param catB
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "teorema", targetNamespace = "http://perez/", className = "perez.Teorema")
    @ResponseWrapper(localName = "teoremaResponse", targetNamespace = "http://perez/", className = "perez.TeoremaResponse")
    @Action(input = "http://perez/perez_metodo/teoremaRequest", output = "http://perez/perez_metodo/teoremaResponse")
    public double teorema(
        @WebParam(name = "catA", targetNamespace = "")
        double catA,
        @WebParam(name = "catB", targetNamespace = "")
        double catB);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://perez/", className = "perez.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://perez/", className = "perez.HelloResponse")
    @Action(input = "http://perez/perez_metodo/helloRequest", output = "http://perez/perez_metodo/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
