
package perez;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "perez_metodo", targetNamespace = "http://perez/", wsdlLocation = "http://localhost:8080/perez_web_parcial1/perez_metodo?wsdl")
public class PerezMetodo_Service
    extends Service
{

    private static final URL PEREZMETODO_WSDL_LOCATION;
    private static final WebServiceException PEREZMETODO_EXCEPTION;
    private static final QName PEREZMETODO_QNAME = new QName("http://perez/", "perez_metodo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/perez_web_parcial1/perez_metodo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PEREZMETODO_WSDL_LOCATION = url;
        PEREZMETODO_EXCEPTION = e;
    }

    public PerezMetodo_Service() {
        super(__getWsdlLocation(), PEREZMETODO_QNAME);
    }

    public PerezMetodo_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PEREZMETODO_QNAME, features);
    }

    public PerezMetodo_Service(URL wsdlLocation) {
        super(wsdlLocation, PEREZMETODO_QNAME);
    }

    public PerezMetodo_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PEREZMETODO_QNAME, features);
    }

    public PerezMetodo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PerezMetodo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PerezMetodo
     */
    @WebEndpoint(name = "perez_metodoPort")
    public PerezMetodo getPerezMetodoPort() {
        return super.getPort(new QName("http://perez/", "perez_metodoPort"), PerezMetodo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PerezMetodo
     */
    @WebEndpoint(name = "perez_metodoPort")
    public PerezMetodo getPerezMetodoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://perez/", "perez_metodoPort"), PerezMetodo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PEREZMETODO_EXCEPTION!= null) {
            throw PEREZMETODO_EXCEPTION;
        }
        return PEREZMETODO_WSDL_LOCATION;
    }

}
